name: Docker Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t flask-input-app .

    - name: Run container
      run: docker run -d -p 5000:5000 --name flask-app flask-input-app

    - name: Wait for app
      run: |
        for i in {1..10}; do
          curl -s http://localhost:5000 && break
          sleep 2
        done

    - name: Verify output
      run: |
        for i in {1..10}; do
         if curl -s http://localhost:5000 | grep -i "Enter"; then
        echo "Form detected"
        exit 0
        fi
          sleep 11
          done
           echo "Form not found"
            exit 1
